treewide_some: fix multiple -Wfamnae warnings that must be audited separately
FIX the following errors so we can have a clean build. This is a
temporary workaround and the code should be audited and properly fixed
up later.

./include/linux/bpf.h:1990:31: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/asm-generic/hyperv-tlfs.h:494:25: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/linux/hyperv.h:767:38: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/linux/kvm_host.h:1842:31: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/linux/bpf.h:1990:31: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/asm-generic/hyperv-tlfs.h:494:25: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/linux/hyperv.h:767:38: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/linux/kvm_host.h:1842:31: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/linux/bpf.h:1990:31: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/asm-generic/hyperv-tlfs.h:494:25: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
...+./include/linux/hyperv.h:767:38: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
..........+...../include/linux/kvm_host.h:1842:31: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/linux/bpf.h:1990:31: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/linux/bpf.h:1990:31: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd.h:109:28: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
drivers/gpu/drm/amd/amdgpu/amdgpu_amdkfd.h:109:28: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]
./include/linux/bpf.h:1990:31: error: structure containing a flexible array member is not at the end of another structure [-Werror=flex-array-member-not-at-end]

Signed-off-by: Gustavo A. R. Silva <gustavoars@kernel.org>