USB: usbfs: Fix flexible-array warning in user-space
The following user-space struct[1] contains some interior declarations
of kernel-space struct usbdevfs_urb:

struct usb_handle {
    ~usb_handle() {
      if (fd != -1) unix_close(fd);
    }

    std::string path;
    int fd = -1;
    unsigned char ep_in;
    unsigned char ep_out;

    size_t max_packet_size;
    unsigned zero_mask;
    unsigned writeable = 1;

    usbdevfs_urb urb_in;
    usbdevfs_urb urb_out;

    bool urb_in_busy = false;
    bool urb_out_busy = false;
    bool dead = false;

    std::condition_variable cv;
    std::mutex mutex;

    // for garbage collecting disconnected devices
    bool mark;

    // ID of thread currently in REAPURB
    pthread_t reaper_thread = 0;
};

The above, together with the fact that zero-length array iso_frame_desc
in struct usbdevfs_urb was replaced with a proper flexible-array member in

	commit 94dfc73e7cf4 ("treewide: uapi: Replace zero-length arrays with flexible-array members")

causes the following warning[2] in user-space:

In file included from /home/mae/.cache/kiss/proc/121205/build/android-tools/vendor/adb/client/usb_linux.cpp:28:
/usr/include/linux/usbdevice_fs.h:134:41: error: flexible array member ‘usbdevfs_urb::iso_frame_desc’ not at end of ‘struct usb_handle’
  134 |         struct usbdevfs_iso_packet_desc iso_frame_desc[];
      |                                         ^~~~~~~~~~~~~~
/home/mae/.cache/kiss/proc/121205/build/android-tools/vendor/adb/client/usb_linux.cpp:76:18: note: next member ‘usbdevfs_urb usb_handle::urb_out’ declared here
   76 |     usbdevfs_urb urb_out;
      |                  ^~~~~~~
/home/mae/.cache/kiss/proc/121205/build/android-tools/vendor/adb/client/usb_linux.cpp:61:8: note: in the definition of ‘struct usb_handle’
   61 | struct usb_handle {
      |        ^~~~~~~~~~

Fix this by creating a union with two arrays at the bottom of struct
usbdevfs_urb, so we can have one (zero-length) array for its use in
user-space and another (C99 flexible) array for its use in kernel-space.

Make use of the __DECLARE_FLEX_ARRAY() helper to declare new flexible-array
member iso_frame_desc_flex. This helper allows for flexible-array
members in unions.

Also, update places where iso_frame_desc_flex should be used instead of
iso_frame_desc.

Reported-by: Mae Dartmann <hello@maedartmann.name>
Fixes: 94dfc73e7cf4 ("treewide: uapi: Replace zero-length arrays with flexible-array members")
Link: https://cs.android.com/android/platform/superproject/+/platform-tools-33.0.3:packages/modules/adb/client/usb_linux.cpp;l=74 [1]
Link: https://github.com/nmeum/android-tools/issues/74 [2]
Signed-off-by: Gustavo A. R. Silva <gustavoars@kernel.org>